# A yarn.lock (Yarn classic, "yarn lockfile v1") grammar for
# lib/packrat.nix. Not JSON/YAML/TOML -- a bespoke, line-oriented,
# fixed-indent format, closely analogous to grammar/gemfile-lock.nix.
# Schema confirmed by surveying 15 real yarn.lock files pulled from
# nixpkgs-adjacent checkouts and node_modules sources (fetched npm
# packages, an internal monorepo lockfile, a large 800+-package
# lockfile), not derived from Yarn's docs alone.
#
# NOTE: Yarn Berry (v2+) lockfiles are a DIFFERENT, YAML-based format (no
# "# yarn lockfile v1" header; uses `__metadata:`, `resolution:`,
# `languageName:`, `linkType:`, `cacheKey:`) -- out of scope for this
# grammar entirely. One 16000-line lockfile found during corpus
# collection turned out to be exactly this Berry format and was excluded;
# see the header comment style of grammar/gemfile-lock.nix for how this
# repo treats a differently-shaped input (correctly fails to parse,
# rather than misparsing).
#
# Why this grammar matters for nixpkgs specifically: today, resolving a
# yarn.lock into Nix-consumable fetch info (as `yarn2nix`/`mkYarnPackage`
# needs -- see pkgs/development/tools/yarn2nix-moretea in nixpkgs, or the
# node2nix/yarn2nix family generally) requires running an external
# Node-based tool, or a network prefetch per package, to compute each
# package's fetch hash. But yarn.lock v1 already embeds a `resolved` URL
# AND an `integrity` (sha1 or sha512, in Subresource Integrity format --
# "sha512-<base64>") per package inline. That's the exact information a
# fixed-output derivation needs, sitting directly in the lockfile, same
# argument as CHECKSUMS in grammar/gemfile-lock.nix: a pure-Nix parser can
# read the whole dependency graph AND every package's fetch info directly
# -- no yarn2nix, no network, no external Node interpreter needed at eval
# time. (Converting the SRI base64 integrity value to the base32 nix-hash
# format a fixed-output derivation wants is a separate, small step, not
# reimplemented here -- see grammar/gemfile-lock.nix's CHECKSUMS/sha256
# case and examples/gemfile-lock-checksums.nix for the equivalent
# hex-to-base32 conversion this grammar's `integrity` field sets up for.)
#
# Top-level shape (confirmed across the whole corpus):
#   # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
#   # yarn lockfile v1
#   (blank line)
#   (blank line)
#   <entry> (blank line <entry>)*
#
# Confirmed structural facts driving this grammar's design:
#   - the two-line header comment and the two blank lines after it are
#     BOTH fixed and universal across the whole corpus (Yarn's own
#     serializer always emits exactly this, byte-for-byte) -- modeled as
#     literal text, not a generic comment-skipping rule.
#   - each entry starts with a "spec line": one or more comma-space (", ")
#     separated <name>@<range> specs, ending in ":\n". A spec is EITHER
#     fully bare (unquoted) OR fully double-quoted; the corpus never
#     mixes bare and quoted specs within one multi-spec line, and a spec
#     is quoted if and only if its name starts with "@" (a scoped
#     package name like "@babel/code-frame") -- because an unquoted
#     "@babel/code-frame@^7.14.5" would be ambiguous with the leading "@"
#     Yarn also uses for... nothing else here, in fact Yarn just always
#     quotes scoped-name specs and never quotes unscoped ones. Modeled as
#     two disjoint choice branches on the FIRST character ("@" or not),
#     not a generic optional-quote wrapper, since that's what the corpus
#     actually does and it makes multi-spec lines unambiguous by
#     first-token dispatch.
#   - a name/range pair is split on the LAST "@" in a spec, not the
#     first: a scoped name itself contains an "@" ("@babel/code-frame"),
#     so "@babel/code-frame@^7.14.5" must split into name
#     "@babel/code-frame" and range "^7.14.5", not name "" and range
#     "babel/code-frame@^7.14.5". Modeled as one greedy capture for the
#     WHOLE spec, split into name/range with `builtins.split`-based
#     rightmost-separator logic in the handler (splitOnLastAt), rather
#     than trying to express "everything up to the LAST @" as a single
#     regex (POSIX ERE via builtins.match has no reliable
#     rightmost-anchor trick for an interior separator without
#     backreferences).
#   - every entry has exactly `version`, `resolved`, `integrity` fields,
#     always in that fixed order, always present (confirmed: zero
#     entries missing any of these three across the whole corpus) --
#     unlike grammar/gemfile-lock.nix's CHECKSUMS, there is no "hash
#     absent" case here. Modeled as fixed non-optional fields, not
#     `opt`-wrapped.
#   - version is always double-quoted free text (confirmed charset across
#     the corpus: alphanumerics, ".", "-" -- covers plain semver,
#     git-describe-style pre-release/build metadata like
#     "1.112.1-106-g5a052bd2", but kept as one opaque greedy capture
#     rather than a hand-rolled semver grammar, same "don't over-specify
#     beyond what's observed" discipline as
#     grammar/gemfile-lock.nix's spec version text).
#   - resolved is always double-quoted, a URL optionally followed by
#     "#<hex>" (a git-style resolved commit/content hash fragment,
#     confirmed present on roughly a third of corpus entries, absent on
#     the rest) -- modeled as one opaque quoted string, not decomposed
#     into URL + fragment, since nothing downstream needs them split
#     (matches how grammar/gemfile-lock.nix keeps a platform-qualified
#     version as one opaque string for the same "consumer doesn't need it
#     split, and splitting risks being wrong about the separator" reason).
#   - integrity is unquoted free text up to end of line, always of the
#     form "sha1-<base64>" or "sha512-<base64>" in the corpus (Subresource
#     Integrity format) -- kept as one opaque string; downstream base32
#     conversion (see file header) only needs the whole value, not a
#     separately-parsed algorithm/digest split.
#   - an entry MAY additionally have a "dependencies:" block and/or an
#     "optionalDependencies:" block, each a 4-space-indented list of
#     "<name> <range>\n" lines (SPACE-separated name/range here, unlike
#     the top-level spec line's "@"-separated form -- confirmed: every
#     dependency sub-line in the corpus is exactly `"<name>" "<range>"\n`
#     or `<name> "<range>"\n`, i.e. the name may or may not be quoted
#     (quoted iff it starts with "@", same rule as top-level specs) but
#     the range is ALWAYS quoted). When both blocks are present,
#     "dependencies:" always comes first (confirmed universal ordering
#     across the corpus) -- modeled as `opt`-wrapped fields in that fixed
#     order, not a generic unordered-key loop.
#   - no escape sequences anywhere in this format outside `resolved`'s
#     double-quoted string (which itself never contains an escaped `"`
#     or `\` in the corpus, confirmed) -- same "no escaping to handle" as
#     grammar/gemfile-lock.nix.
#   - entries are separated by exactly one blank line; the corpus has zero
#     double-blank-line gaps or blank lines mid-entry -- modeled with
#     `star`/`plus` on whole "entry + trailing blank line" units, same
#     "sourceBlock" pattern grammar/gemfile-lock.nix uses.
#   - the file's last entry has NO trailing blank line after it (the
#     final `integrity`/dependency line is immediately followed by
#     end-of-input) -- modeled by requiring exactly one blank-line
#     separator BETWEEN entries (star of [entry, blankLine], with a
#     final un-separated entry), not a blank line after every entry.
#
# Deliberately out of scope:
#   - Yarn Berry / v2+ lockfiles (see NOTE above -- different format
#     entirely, detected by this grammar's own fixed 2-line header
#     literal match, which a Berry lockfile's different header fails)
#   - `resolution:`/`checksum:`/`cacheKey:`/`languageName:`/`linkType:`
#     fields (Berry-only, never seen in a v1 lockfile in the corpus)
#   - preserving comment lines beyond the fixed 2-line header (v1
#     lockfiles have no other comment syntax to preserve)
# A malformed, differently-versioned, or otherwise differently-structured
# yarn.lock correctly fails to parse rather than silently mis-parsing,
# same discipline as every other grammar in this repo.
let
  # Splits a spec string on its LAST "@" into { name; range; } -- see file
  # header for why last-@ (not first-@) is the correct split point for
  # scoped package names. `builtins.match` has no direct "everything up
  # to the last occurrence of X" primitive, so this walks the string via
  # `builtins.split` (which DOES report every occurrence) and keeps the
  # final segment as the range, joining everything before it back into
  # the name.
  splitOnLastAt =
    spec:
    let
      # `builtins.split "@" spec` returns a list alternating
      # [literalPiece, ["@"], literalPiece, ["@"], ..., literalPiece] --
      # odd indices are always exactly `["@"]` (the regex has no capture
      # group besides the whole match), even indices are the literal
      # pieces between separators.
      parts = builtins.split "@" spec;
      pieces = builtins.filter (p: !(builtins.isList p)) parts;
      n = builtins.length pieces;
    in
    {
      name = builtins.concatStringsSep "@" (builtins.genList (i: builtins.elemAt pieces i) (n - 1));
      range = builtins.elemAt pieces (n - 1);
    };

  # "end of line": an actual newline, or end of input (the file's last
  # line need not have a trailing newline).
  lineEnd = {
    choice = [
      { regex = "(\r?\n)"; }
      {
        not = {
          regex = "(.)";
        };
      }
    ];
  };

  blankLine = {
    lit = "\n";
  };

  # A single spec's full text ("name@range", possibly containing internal
  # "@"s from a scoped name) -- stops at "," (multi-spec separator) or the
  # closing quote/colon that ends the whole spec line, whichever grammar
  # context uses it. Split into name/range by splitOnLastAt in the
  # handler, not by the grammar itself (see file header).
  bareSpecText = {
    regex = "([^,\":\r\n]+)";
  };
  quotedSpecText = {
    regex = "([^\",]+)";
  };

  bareSpec = {
    action = {
      e = bareSpecText;
      f = splitOnLastAt;
    };
  };
  quotedSpec = {
    action = {
      e = [
        { lit = "\""; }
        quotedSpecText
        { lit = "\""; }
      ];
      f = v: splitOnLastAt (builtins.elemAt v 1);
    };
  };

  # A whole spec line's comma-separated list, entirely bare or entirely
  # quoted -- see file header for why a line is never mixed. Dispatched
  # by first character ("@" selects the quoted branch, since only
  # scoped-name specs are ever quoted): ordinary PEG first-token ordered
  # choice, tried in this order so a bare spec (the common case) doesn't
  # pay for a failed quote-branch attempt first.
  specList = {
    choice = [
      [
        bareSpec
        {
          star = [
            { lit = ", "; }
            bareSpec
          ];
        }
      ]
      [
        quotedSpec
        {
          star = [
            { lit = ", "; }
            quotedSpec
          ];
        }
      ]
    ];
  };

  specLine = {
    action = {
      e = [
        specList
        { lit = ":"; }
        lineEnd
      ];
      f =
        v:
        let
          list = builtins.elemAt v 0;
        in
        [ (builtins.elemAt list 0) ] ++ map (p: builtins.elemAt p 1) (builtins.elemAt list 1);
    };
  };

  # "  <key> <value>\n" -- used for version/integrity (bare value) and
  # resolved (quoted value); `quoted` picks which.
  scalarField = key: quoted: {
    action = {
      e = [
        { lit = "  ${key} "; }
      ]
      ++ (
        if quoted then
          [
            { lit = "\""; }
            { regex = "([^\"]*)"; }
            { lit = "\""; }
          ]
        else
          [ { regex = "([^\r\n]+)"; } ]
      )
      ++ [ lineEnd ];
      f = v: builtins.elemAt v (if quoted then 2 else 1);
    };
  };

  # A dependency-block name: quoted iff scoped (leading "@"), same rule
  # as top-level specs (see file header) -- but here name and range are
  # two SEPARATE space-separated tokens, not one "@"-joined spec, so no
  # splitOnLastAt is needed.
  depName = {
    choice = [
      {
        action = {
          e = [
            { lit = "\""; }
            { regex = "([^\"]+)"; }
            { lit = "\""; }
          ];
          f = v: builtins.elemAt v 1;
        };
      }
      { regex = "([^ \r\n]+)"; }
    ];
  };

  # "    <name> \"<range>\"\n" -- a single dependencies:/optionalDependencies:
  # sub-line, 4-space indented (confirmed fixed across the corpus, same
  # "Yarn's own serializer, not a typo" reasoning as
  # grammar/gemfile-lock.nix's fixed indents).
  depLine = {
    action = {
      e = [
        { lit = "    "; }
        depName
        { lit = " \""; }
        { regex = "([^\"]*)"; }
        { lit = "\""; }
        lineEnd
      ];
      f = v: {
        name = builtins.elemAt v 1;
        range = builtins.elemAt v 3;
      };
    };
  };

  # `{plus=depLine;}`'s raw value is `[first star-list]` (see
  # lib/packrat.nix: plus desugars to `[e {star=e;}]`), not a flat list --
  # flattened here via `action` so entry's handler can just index straight
  # into a plain list of {name;range;} attrsets.
  depsBlock = key: {
    action = {
      e = [
        { lit = "  ${key}:\n"; }
        { plus = depLine; }
      ];
      f =
        v:
        let
          p = builtins.elemAt v 1;
        in
        [ (builtins.elemAt p 0) ] ++ builtins.elemAt p 1;
    };
  };

  entry = {
    action = {
      e = [
        specLine
        (scalarField "version" true)
        (scalarField "resolved" true)
        (scalarField "integrity" false)
        { opt = depsBlock "dependencies"; }
        { opt = depsBlock "optionalDependencies"; }
      ];
      f = v: {
        specs = builtins.elemAt v 0;
        version = builtins.elemAt v 1;
        resolved = builtins.elemAt v 2;
        integrity = builtins.elemAt v 3;
        dependencies =
          let
            d = builtins.elemAt v 4;
          in
          if d == null then [ ] else d;
        optionalDependencies =
          let
            d = builtins.elemAt v 5;
          in
          if d == null then [ ] else d;
      };
    };
  };

  document = [
    { lit = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"; }
    { lit = "# yarn lockfile v1\n"; }
    { lit = "\n\n"; }
    entry
    {
      star = [
        blankLine
        entry
      ];
    }
    {
      opt = {
        regex = "(\r?\n)";
      };
    } # a lockfile's final line may or may not end in a newline
    {
      not = {
        regex = "(.)";
      };
    } # require the ENTIRE input consumed, not just a prefix
  ];

  documentHandler =
    v: [ (builtins.elemAt v 3) ] ++ map (pair: builtins.elemAt pair 1) (builtins.elemAt v 4);

  grammar = {
    DOCUMENT = document;
  };
  handlers = {
    DOCUMENT = documentHandler;
  };
in
{
  inherit grammar handlers;
}
